// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5NgEmp-j4wI9DRJM-dW9qSy_VswXGrM8',
    appId: '1:739076365807:web:5742fb751f11e1822e2a1a',
    messagingSenderId: '739076365807',
    projectId: 'pcte-events',
    authDomain: 'pcte-events.firebaseapp.com',
    databaseURL: 'https://pcte-events-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pcte-events.appspot.com',
    measurementId: 'G-69Y9VKJX53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL63D1vxS_akqkc_OnVqJ42JqXv8oU8kA',
    appId: '1:739076365807:android:c041287c6b691e062e2a1a',
    messagingSenderId: '739076365807',
    projectId: 'pcte-events',
    databaseURL: 'https://pcte-events-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pcte-events.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDf7akNSCnHbUri6U1GDy0aSTMYdih278',
    appId: '1:739076365807:ios:ff6ff209884674c32e2a1a',
    messagingSenderId: '739076365807',
    projectId: 'pcte-events',
    databaseURL: 'https://pcte-events-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pcte-events.appspot.com',
    androidClientId: '739076365807-s4mu3nlev3r9ehhurcikg8d64ug39kse.apps.googleusercontent.com',
    iosClientId: '739076365807-cv7rcahgv77ln3vop6g3itfgobiuag0e.apps.googleusercontent.com',
    iosBundleId: 'com.dazai.pcteEvents',
  );
}
